apiVersion: v1
kind: ConfigMap
metadata:
  name: library-mysql-config
data:
  MYSQL_PORT: "3306"
  MYSQL_USER: libraryapp
  MYSQL_DATABASE: librarydb

---
apiVersion: v1
kind: Secret
metadata:
  name: library-mysql-secret
type: Opaque
data:
  MYSQL_PASSWORD: MTIzNDU2NzhhYmM=
  MYSQL_ROOT_PASSWORD: MTIzNDU2NzhhYmM=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  libraryapp.sql: |
    GRANT ALL PRIVILEGES ON librarydb.* TO 'libraryapp'@'%';
    FLUSH PRIVILEGES;
    CREATE DATABASE IF NOT EXISTS librarydb;
