apiVersion: v1
kind: ConfigMap
metadata:
  name: library-mysql-config
data:
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: sparklmsdb

---
apiVersion: v1
kind: Secret
metadata:
  name: library-mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg=
