apiVersion: v1
kind: Pod
metadata:
  name: library-mysql-server
  labels: 
    app: library-mysql-server
spec:
  containers:
    - name: library-mysql-server
      image: mysql:latest
      imagePullPolicy: "Always"
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: library-mysql-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: library-mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: library-mysql-config
              key: MYSQL_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: library-mysql-secret
              key: MYSQL_ROOT_PASSWORD
      volumeMounts:
        - name: library-db-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d

  volumes:
    - name: library-db-storage
      persistentVolumeClaim:
        claimName: library-mysql-pvc
    - name: mysql-initdb
      configMap:
        name: mysql-initdb-config
        

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: library-mysql-server
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      