apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-library-app
  template:
    metadata:
      labels:
        app: java-library-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: java-library-app
          image: "mohammadrony/java-library-app:${BUILD_NUMBER}"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
            
---
apiVersion: v1
kind: Service
metadata:
  name: library-app-service
spec:
  selector:
    app: java-library-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
  